.\" vim: tw=75
.TH dnsip 1

.SH NAME
dnsip \- lookup IP addresses

.SH SYNOPSIS
dnsip 
[
.I fqdn
]

.SH DESCRIPTION
\fBdnsip\fR resolves \fIfqdn\fR and prints the IP addresses of \fIfqdn\fR
on a single line. If \fIfqdn\fR does not exist, \fBdnsip\fR prints a blank
line. You can list several \fIfqdn\fR's; \fBdnsip\fR prints each result on
a separate line.

Normally \fBdnsip\fR exits 0. If \fBdnsip\fR encounters a temporary problem
that prevents it from determining the list of IP addresses, it prints an
error message and exits 111. It also exits 111 if it is not able to write
the ip address to descriptor 1. The same comments apply to the other
programs described here.

.SH SEE ALSO
dnsipq(1),
dnsname(1),
dnsmx(1),
dnstxt(1),
dnsqr(1),
dnsq(1),
dnstrace(1)

http://cr.yp.to/djbdns.html
