.\" vim: tw=75
.TH dnsqr 1

.SH NAME
dnsqr \- asks for records of type 
.I t
under the domain name 
.I fqdn

.SH SYNOPSIS
.B dnsqr 
.I t
.I fqdn

.SH DESCRIPTION
\fBdnsqr\fR asks for records of type \fIt\fR under the domain name
\fIfqdn\fR. It prints the results in a human-readable format, more compact
than the \fIdig\fR output format.

\fIt\fR may be a name or number. Currently recognized names:
.IR any ,
.IR a ,
.IR ns ,
.IR mx ,
.IR ptr ,
.IR txt ,
.IR cname ,
.IR soa ,
.IR hinfo ,
.IR rp ,
.IR sig ,
.IR key ,
.IR aaaa ,
.IR axfr .
Note that, if you want to perform a zone transfer, you should use
\fBaxfr-get\fR(8), not \fBdnsqr\fR(1), \fBaxfrdns\fR(8).

\fBdnsqr\fR is available in djbdns 1.01 and above. \fBdnsqr\fR exits 111 if
it is unable to parse, runs out of memory or unable to write results to
descriptor 1.

.SH SEE ALSO
dnsip(1),
dnsipq(1),
dnsmx(1),
dnstxt(1),
dnsname(1),
dnsq(1),
dnstrace(1),
tinydns-get(1)

http://cr.yp.to/djbdns.html
