#!/bin/sh
set -x
make clean
make distclean
ver=1.05
mv debian ../dnsDebian
cd ..
if [ -f $HOME/.rpmmacros ] ; then
	topdir=`grep ^%_topdir $HOME/.rpmmacros|awk '{print $2}'`
else
	topdir=$HOME/rpmbuild
fi
tar cf - tinydnssec-$ver | gzip -c > $topdir/SOURCES/tinydnssec-$ver.tar.gz
mv dnsDebian tinydnssec-$ver/debian
cd tinydnssec-$ver
rpmbuild -ba --clean tinydnssec.spec
