#!/bin/sh
if test -f $HOME/.rpmmacros
then
	topdir=`grep ^%_topdir $HOME/.rpmmacros | awk '{print $2}'`
	if test -n "$topdir"
	then
		rpmbuild=$topdir
	else
		rpmbuild=$HOME/rpmbuild
	fi
else
	rpmbuild=$HOME/rpmbuild
fi
version=$(cat conf-version)
cd ..
if [ -d stage ] ; then
	/bin/rm -rf stage
fi
mkdir stage
if [ $? -ne 0 ] ; then
	exit 1
fi
cp -rp tinydnssec-$version stage
if [ $? -ne 0 ] ; then
	exit 1
fi
cd stage/tinydnssec-$version
if [ $? -ne 0 ] ; then
	exit 1
fi
make -s clean
make -s distclean
cd ..
tar \
	--exclude="tinydnssec-$version/.git" \
	--exclude="tinydnssec-$version/debian" \
	--exclude="tinydnssec-$version/RCS" \
	-cf - tinydnssec-"$version" \
			| gzip -c > $rpmbuild/SOURCES/tinydnssec-"$version".tar.gz
cd ..
dist=`uname -r |cut -d . -f4`
if [ $# -gt 0 ] ; then
	release=$1
else
	if [ -f /usr/bin/tinydns ] ; then
		tdist=$(rpm -qf /usr/bin/tinydns|cut -d- -f3|cut -d. -f3)
		if [ " $dist" = " $tdist" ] ; then
			tversion=$(rpm -qf /usr/bin/tinydns|cut -d- -f2)
			if [ "$tversion" = "$version" ] ; then
				release=$(rpm -qf /usr/bin/tinydns | cut -d- -f3 | cut -d. -f2)
				release=$(expr $release + 1)
			else
				release=1
			fi
		else
			release=1
		fi
	else
		release=1
	fi
fi
echo -n "Build RPM for tinydnssec-"$version"-1."$release" (Y/N) - "
read key
if [ " $key" = " Y" -o " $key" = " y" ] ; then
	cp stage/tinydnssec-$version/tinydnssec.spec /tmp
	/bin/rm -rf stage
	tmprel=`cat tinydnssec-$version/conf-release 2>/dev/null`
	if [ ! " $tmprel" = " 1.$release" ] ; then
		echo 1.$release > tinydnssec-$version/conf-release
		cd tinydnssec-$version
		make tinydnssec.spec
		cp tinydnssec.spec /tmp
		cd debian
		make
	fi
	rpmbuild -ba --clean /tmp/tinydnssec.spec
	/bin/rm -f /tmp/tinydnssec.spec
	build_arch=`rpmbuild --showrc|grep "^build arch" | awk '{print $4}'`
	rpm --addsign $rpmbuild/RPMS/$build_arch/tinydnssec-"$version"-"1.$release".$dist.$build_arch.rpm
	rpm --addsign $rpmbuild/SRPMS/tinydnssec-"$version"-"1.$release".$dist.src.rpm
	echo -n "RPM lint for tinydnssec-"$version"-1."$release" (Y/N) - "
	read key
	if [ " $key" = " Y" -o " $key" = " y" ] ; then
		(
		echo tinydnssec-"$version"-"1.$release".$dist.$build_arch
		rpmlint $rpmbuild/RPMS/$build_arch/tinydnssec-"$version"-"1.$release".$dist.$build_arch.rpm
		echo ------------------------
		echo tinydnssec-"$version"-"1.$release".$dist.src.rpm
		rpmlint $rpmbuild/SRPMS/tinydnssec-"$version"-"1.$release".$dist.src.rpm
		echo ------------------------
		) 2>&1 | less
	fi
else
	/bin/rm -rf stage
fi
echo -n "Remove Source (Y/N) - "
read key
if [ " $key" = " Y" -o " $key" = " y" ] ; then
	/bin/rm -f $rpmbuild/SOURCES/tinydnssec-"$version".tar.gz
fi


