name: tinydnssec FreeBSD CI

on:
  push:
    paths:
      - '**/tinydnssec-x/**'
      - .github/workflows/tinydnssec-freebsd.yml
      - '!**/tinydnssec-x/tinydnssec.spec.in'
      - '!**/tinydnssec-x/debian/*'
      - '!**/doc/*'
      - '!**.md'

jobs:
  testfreebsd:
    runs-on: macos-latest
    name: FreeBSD
    env:
      MYTOKEN : ${{ secrets.MYTOKEN }}
      MYTOKEN2: "value2"
    steps:
    - uses: actions/checkout@v2
      with:
        path: main
    - uses: actions/checkout@v2
      with:
        repository: mbhangui/libqmail
        path: libqmail
    - name: build tinydnssec
      id: FreeBSD
      uses: vmactions/freebsd-vm@v0.1.2
      with:
        envs: 'MYTOKEN MYTOKEN2'
        usesh: true
        prepare: pkg install -y curl bash automake autoconf libtool pkgconf libsodium
        - name: install_qmail
          run: cd libqmail; ./default.configure; make; make install-strip
        - name: tinydnssec
          run: cd main/tinydnssec-x; ./default.configure; make; make install-strip
        - name: dq
          run: cd main/tinydnssec-x/dq-20161210; make; sh ./make-install.sh
        - name: find stuff
          run: find / -name ev.h -print; find / -name libev'*' -print
        - name: curvedns
          run: cd main/tinydnssec-x/curvedns-0.88; ./default.configure; make; make install-strip
