name: tinydnssec FreeBSD CI

on:
  push:
    paths:
      - '**/tinydnssec-x/**'
      - .github/workflows/tinydnssec-freebsd.yml
      - '!**/tinydnssec-x/tinydnssec.spec.in'
      - '!**/tinydnssec-x/debian/*'
      - '!**/doc/*'
      - '!**.md'

jobs:
  testfreebsd:
    runs-on: macos-latest
    name: FreeBSD
    env:
      MYTOKEN : ${{ secrets.MYTOKEN }}
      MYTOKEN2: "value2"
    steps:
    - uses: actions/checkout@v2
      with:
        path: main
    - uses: actions/checkout@v2
      with:
        repository: mbhangui/libqmail
        path: libqmail
    - name: build tinydnssec
      id: FreeBSD
      uses: vmactions/freebsd-vm@v0.1.2
      with:
        envs: 'MYTOKEN MYTOKEN2'
        usesh: true
        prepare: pkg install -y curl bash automake autoconf libtool pkgconf
        run: |
          cd libqmail; ./default.configure; make; make install-strip
          cd ../main/tinydnssec-x; ./default.configure; make
          cd dq-20161210; make
