name: tinydnssec Ubuntu Mac OSX CI

on:
  push:
    paths:
      - '**/tinydnssec-x/**'
      - .github/workflows/tinydnssec-c-cpp.yml
      - '!**/tinydnssec-x/tinydnssec.spec.in'
      - '!**/tinydnssec-x/debian/*'
      - '!**/doc/*'
      - '!**.md'

jobs:
  build:
    name: ${{ matrix.host }}-${{ matrix.config.name }}
    runs-on: ${{ matrix.host }}
    strategy:
      fail-fast: false
      matrix:
        host: [ubuntu-latest, macos-latest]
    
    steps:
    - name: extra_packages
      run: |
        if [ "${OS}" = "macos-latest" ] ; then brew install automake autoconf libtool pkgconfig openssl libsodium libev; fi
        if [ "${OS}" = "ubuntu-latest" ] ; then sudo apt-get install gcc g++ automake autoconf libtool libssl-dev libsodium-dev libev-dev; fi
      env:
        OS: ${{ matrix.host }}

    - name: checkout_main
      uses: actions/checkout@v2
      with:
        path: main
      
    - name: checkout_qmail
      uses: actions/checkout@v2
      with:
        repository: mbhangui/libqmail
        path: libqmail

    - name: install_qmail
      run: cd libqmail;env CPPFLAGS="-I/usr/local/opt/openssl@1.1/include" LDFLAGS="-L/usr/local/opt/openssl@1.1/lib" ./default.configure; env CPPFLAGS="-I/usr/local/opt/openssl@1.1/include" LDFLAGS="-L/usr/local/opt/openssl@1.1/lib" make; sudo make install-strip
    - name: build_tinydnssec
      run: cd main/tinydnssec-x; env CPPFLAGS="-I/usr/local/opt/openssl@1.1/include" LDFLAGS="-L/usr/local/opt/openssl@1.1/lib" ./default.configure; env CPPFLAGS="-I/usr/local/opt/openssl@1.1/include" LDFLAGS="-L/usr/local/opt/openssl@1.1/lib" make
    - name: build_dq
      run: cd main/tinydnssec-x/dq-20161210; make
    - name: build_curvedns
      run: cd main/tinydnssec-x/curvedns-0.88; env CPPFLAGS="-I../dq-20161210/crypto" ./default.configure; env CPPFLAGS="-I../dq-20161210/crypto" make
      env:
        OS: ${{ matrix.host }}

