name: tinydnssec Ubuntu, Mac OSX CI

on:
  push:
    branches:
      - master
    paths:
      - '**/tinydnssec-1.05/**'
      - .github/workflows/tinydnssec-c-cpp.yml
      - '!**/tinydnssec-1.05/tinydnssec.spec.in'
      - '!**/tinydnssec-1.05/debian/*'
      - '!**/tinydnssec-1.05x/doc/*'
      - '!**.md'
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: ${{ matrix.host }}-${{ matrix.config.name }}
    runs-on: ${{ matrix.host }}
    strategy:
      fail-fast: false
      matrix:
        host: [ubuntu-latest, macos-latest]
    
    steps:
    - name: extra_packages
      run: |
        if [ "${OS}" = "macos-latest" ] ; then brew install automake autoconf libtool pkgconfig openssl; fi
        if [ "${OS}" = "ubuntu-latest" ] ; then sudo apt-get install gcc g++ automake autoconf libtool libssl-dev libev-dev ; fi
      env:
        OS: ${{ matrix.host }}

    - name: checkout_main
      uses: actions/checkout@v2
      with:
        path: main
      
    - name: checkout_qmail
      uses: actions/checkout@v2
      with:
        repository: mbhangui/libqmail
        path: libqmail

    - name: install_qmail
      run: cd libqmail;env CPPFLAGS="-I/usr/local/opt/openssl@1.1/include" LDFLAGS="-L/usr/local/opt/openssl@1.1/lib" ./default.configure; env CPPFLAGS="-I/usr/local/opt/openssl@1.1/include" LDFLAGS="-L/usr/local/opt/openssl@1.1/lib" make; sudo make install-strip
    - name: build_tinydnssec
      run: cd main/tinydnssec-1.05; ./default.configure; make
    - name: build_dq
      run: cd main/tinydnssec-1.05/dq-20161210; make
    - name: build_curvedns
      run: cd main/tinydnssec-1.05/curvedns-0.88; ./configure.nacl; ./configure.curvedns; make

